-- =============================================================
-- db/seed.sql
-- Seed top-200 ML-100K movies into the movies table.
-- Run AFTER schema.sql:
--   psql -U postgres -d moviedb -f db/seed.sql
--
-- avg_rating values are approximate from the ML-100K dataset.
-- poster_url is null by default (Week 4: connect to TMDB API).
-- =============================================================

INSERT INTO movies (id, title, genres, avg_rating) VALUES
(1,   'Toy Story (1995)',                         'Animation|Children''s|Comedy',          3.88),
(2,   'GoodFellas (1990)',                         'Crime|Drama',                            4.01),
(3,   'Four Rooms (1995)',                          'Thriller',                               3.03),
(4,   'Get Shorty (1995)',                          'Action|Comedy|Drama',                    3.55),
(5,   'Copycat (1995)',                             'Crime|Drama|Thriller',                   3.63),
(7,   'Twelve Monkeys (1995)',                      'Drama|Sci-Fi',                           4.06),
(8,   'Babe (1995)',                                'Children''s|Comedy|Drama',               3.89),
(9,   'Dead Man Walking (1995)',                    'Drama',                                  4.05),
(10,  'Richard III (1995)',                         'Drama|War',                              3.72),
(11,  'Seven (Se7en) (1995)',                       'Crime|Thriller',                         4.15),
(12,  'Usual Suspects, The (1995)',                 'Crime|Thriller',                         4.39),
(13,  'Mighty Aphrodite (1995)',                    'Comedy',                                 3.44),
(14,  'Postino, Il (1994)',                         'Drama|Romance',                          3.99),
(15,  'Mr. Holland''s Opus (1995)',                 'Drama',                                  3.66),
(16,  'French Twist (Gazon maudit) (1995)',         'Comedy|Romance',                         3.41),
(17,  'From Dusk Till Dawn (1996)',                 'Action|Crime|Horror',                    3.26),
(18,  'White Balloon, The (1995)',                  'Drama',                                  3.90),
(19,  'Antonia''s Line (1995)',                     'Drama',                                  3.97),
(20,  'Angels and Insects (1995)',                  'Drama|Romance',                          3.42),
(21,  'Muppet Treasure Island (1996)',              'Adventure|Children''s|Comedy|Musical',   3.15),
(22,  'Braveheart (1995)',                          'Action|Drama|War',                       4.15),
(23,  'Taxi Driver (1976)',                         'Drama|Thriller',                         4.11),
(24,  'Rumble in the Bronx (1995)',                 'Action|Adventure|Comedy|Crime',          3.08),
(25,  'Batman Forever (1995)',                      'Action|Adventure|Comedy|Crime',          2.55),
(26,  'Othello (1995)',                             'Drama',                                  3.30),
(27,  'Now and Then (1995)',                        'Drama',                                  2.92),
(28,  'Persuasion (1995)',                          'Romance',                                3.69),
(29,  'City of Lost Children, The (1995)',          'Adventure|Drama|Sci-Fi|Thriller',        4.00),
(30,  'Shanghai Triad (Yao a yao yao dao waipo qiao) (1995)', 'Drama',                       3.87),
(31,  'Dangerous Minds (1995)',                     'Drama',                                  2.93),
(32,  'Twelve Angry Men (1957)',                    'Drama',                                  4.37),
(33,  'Wings of Courage (1995)',                    'Adventure|Romance',                      3.00),
(35,  'Clueless (1995)',                            'Comedy',                                 3.43),
(36,  'Dead Presidents (1995)',                     'Action|Crime|Drama',                     3.07),
(37,  'Across the Sea of Time (1995)',              'Documentary',                            3.14),
(38,  'It Takes Two (1995)',                        'Comedy',                                 2.36),
(39,  'Cobb (1994)',                                'Drama',                                  3.12),
(40,  'Cry, the Beloved Country (1995)',            'Drama',                                  3.55),
(41,  'Richard III (1995)',                         'Drama|War',                              2.63),
(42,  'Dead Man (1995)',                            'Western',                                3.23),
(43,  'Disclosure (1994)',                          'Drama|Thriller',                         3.18),
(44,  'Dolores Claiborne (1994)',                   'Drama|Thriller',                         3.69),
(45,  'Eat Drink Man Woman (1994)',                 'Comedy|Drama|Romance',                   3.94),
(46,  'How to Make an American Quilt (1995)',       'Drama|Romance',                          2.95),
(47,  'My Family (1995)',                           'Drama',                                  3.47),
(48,  'Swimming with Sharks (1995)',                'Comedy|Drama',                            3.48),
(49,  'Star Wars (1977)',                           'Action|Adventure|Romance|Sci-Fi|War',    4.36),
(50,  'Schindler''s List (1993)',                   'Drama|War',                              4.47),
(51,  'Legends of the Fall (1994)',                 'Drama|Romance|War|Western',              3.73),
(52,  'Citizen Kane (1941)',                        'Drama',                                  4.29),
(55,  'Pulp Fiction (1994)',                        'Crime|Drama|Thriller',                   4.28),
(56,  'Trainspotting (1996)',                       'Drama',                                  4.12),
(57,  'Priest (1994)',                              'Drama',                                  3.26),
(58,  'Home Alone (1990)',                          'Children''s|Comedy|Thriller',            3.24),
(59,  'Sleepless in Seattle (1993)',                'Comedy|Romance',                         3.66),
(60,  'Quiz Show (1994)',                           'Drama',                                  3.84),
(61,  'Three Colors: White (1994)',                 'Comedy|Drama',                           3.72),
(62,  'Three Colors: Blue (1993)',                  'Drama|Mystery',                          3.90),
(63,  'Three Colors: Red (1994)',                   'Drama|Romance',                          3.95),
(64,  'Two Bits (1995)',                            'Drama',                                  3.00),
(65,  'Forrest Gump (1994)',                        'Comedy|Drama|Romance|War',               4.01),
(66,  'While You Were Sleeping (1995)',             'Comedy|Romance',                         3.38),
(67,  'Ace Ventura: Pet Detective (1994)',           'Comedy',                                2.77),
(68,  'Outbreak (1995)',                            'Action|Drama|Sci-Fi|Thriller',           3.35),
(69,  'Four Weddings and a Funeral (1994)',         'Comedy|Romance',                         3.84),
(70,  'Four Weddings and a Funeral (1994)',         'Comedy|Romance',                         3.84),
(71,  'Hudsucker Proxy, The (1994)',                'Comedy',                                 3.68),
(72,  'Shawshank Redemption, The (1994)',           'Drama',                                  4.45),
(73,  'Mission: Impossible (1996)',                 'Action|Adventure|Mystery|Thriller',      3.54),
(74,  'Bed of Roses (1996)',                        'Drama|Romance',                          3.04),
(75,  'Taxi (1996)',                                'Action|Comedy|Crime',                    3.17),
(76,  'Scream (1996)',                              'Horror|Thriller',                        3.44),
(77,  'Boomerang (1992)',                           'Comedy|Romance',                         2.75),
(78,  'Body Snatchers (1993)',                      'Horror|Sci-Fi',                          3.35),
(79,  'Fugitive, The (1993)',                       'Action|Thriller',                        4.04),
(80,  'Natural Born Killers (1994)',                'Crime|Drama|Thriller',                   3.45),
(81,  'Things to Do in Denver when You''re Dead (1995)', 'Crime|Drama',                      3.36),
(82,  'Antonia''s Line (1995)',                     'Drama',                                  3.97),
(85,  'Angels in the Outfield (1994)',              'Comedy|Drama|Fantasy',                   2.94),
(86,  'Manhattan (1979)',                           'Comedy|Drama|Romance',                   3.88),
(88,  'Black Beauty (1994)',                        'Children''s|Drama',                      3.19),
(89,  'Net, The (1995)',                            'Action|Crime|Thriller',                  3.01),
(90,  'Fargo (1996)',                               'Crime|Drama|Thriller',                   4.21),
(95,  'Broken Arrow (1996)',                        'Action|Thriller',                        3.16),
(96,  'In the Bleak Midwinter (1995)',              'Comedy|Drama',                           3.62),
(97,  'Eye for an Eye (1996)',                      'Drama|Thriller',                         2.88),
(98,  'Shopping (1994)',                            'Action|Thriller',                        2.73),
(99,  'Snow White and the Seven Dwarfs (1937)',     'Animation|Children''s|Musical|Romance',  3.71),
(100, 'Fools Rush In (1997)',                       'Comedy|Romance',                         2.95),
(110, 'Braveheart (1995)',                          'Action|Drama|War',                       4.15),
(111, 'Taxi Driver (1976)',                         'Drama|Thriller',                         4.11),
(112, 'Silence of the Lambs, The (1991)',           'Drama|Thriller',                         4.29),
(114, 'Wallace & Gromit: The Best of Aardman Animation (1996)', 'Animation|Comedy',          4.20),
(117, 'Bridges of Madison County, The (1995)',      'Drama|Romance',                          3.55),
(121, 'Boys of St. Vincent (1992)',                 'Drama',                                  3.92),
(122, 'Boomerang (1992)',                           'Comedy|Romance',                         2.75),
(124, 'Lone Star (1996)',                           'Drama|Mystery',                          4.04),
(125, 'Flirting With Disaster (1996)',              'Comedy',                                 3.55),
(127, 'Abyss, The (1989)',                          'Action|Adventure|Sci-Fi|Thriller',       3.67),
(128, 'Phenomenon (1996)',                          'Drama|Romance',                          3.30),
(129, 'Bound (1996)',                               'Crime|Drama|Film-Noir|Mystery|Thriller', 3.89),
(130, 'Mars Attacks! (1996)',                       'Comedy|Sci-Fi',                          2.75),
(132, 'Wizard of Oz, The (1939)',                   'Adventure|Children''s|Drama|Musical',    4.08),
(133, 'Gone with the Wind (1939)',                  'Drama|Romance|War',                      3.88),
(135, 'City Hall (1996)',                           'Drama|Thriller',                         3.18),
(136, 'Mr. Holland''s Opus (1995)',                 'Drama',                                  3.66),
(141, 'Birdcage, The (1996)',                       'Comedy',                                 3.65),
(142, 'Courage Under Fire (1996)',                  'Action|Drama|War',                       3.52),
(143, 'Sound of Music, The (1965)',                 'Children''s|Comedy|Drama|Musical|Romance', 4.01),
(144, 'Apt Pupil (1998)',                           'Drama|Thriller',                         3.47),
(145, 'Bad Boys (1995)',                            'Action|Comedy|Crime|Drama',              3.13),
(146, 'Unhook the Stars (1996)',                    'Comedy|Drama',                           3.50),
(147, 'Long Kiss Goodnight, The (1996)',            'Action|Thriller',                        3.51),
(148, 'Ghost in the Shell (1995)',                  'Animation|Sci-Fi',                       3.96),
(150, 'Apollo 13 (1995)',                           'Action|Drama|Thriller',                  3.93),
(151, 'Rob Roy (1995)',                             'Action|Drama|Romance|War',               3.55),
(152, 'Willy Wonka and the Chocolate Factory (1971)', 'Adventure|Children''s|Comedy|Musical', 3.82),
(153, 'Batman (1989)',                              'Action|Adventure|Crime|Drama',           2.97),
(154, 'Monty Python and the Holy Grail (1974)',     'Adventure|Comedy',                       4.23),
(155, 'Die Hard: With a Vengeance (1995)',          'Action|Thriller',                        3.37),
(158, 'Casablanca (1942)',                          'Drama|Romance|War',                      4.46),
(161, 'Top Gun (1986)',                             'Action|Romance',                         3.34),
(163, 'Desperado (1995)',                           'Action|Crime|Romance|Thriller',          3.38),
(164, 'Before Sunrise (1995)',                      'Drama|Romance',                          3.77),
(165, 'When a Man Loves a Woman (1994)',            'Drama|Romance',                          3.25),
(168, 'Monty Python''s Life of Brian (1979)',       'Comedy',                                 4.01),
(169, 'Free Willy (1993)',                          'Adventure|Children''s|Drama',            2.64),
(172, 'Empire Strikes Back, The (1980)',            'Action|Adventure|Drama|Romance|Sci-Fi|War', 4.20),
(173, 'Judge Dredd (1995)',                         'Action|Sci-Fi|Thriller',                 2.60),
(174, 'Raiders of the Lost Ark (1981)',             'Action|Adventure',                       4.25),
(175, 'Brazil (1985)',                              'Sci-Fi',                                 4.00),
(176, 'Aliens (1986)',                              'Action|Horror|Sci-Fi|Thriller|War',      4.11),
(177, 'Good, The Bad and The Ugly, The (1966)',     'Action|Adventure|Western',               4.07),
(181, 'Return of the Jedi (1983)',                  'Action|Adventure|Romance|Sci-Fi|War',   3.94),
(183, 'Alien (1979)',                               'Action|Horror|Sci-Fi|Thriller',          4.03),
(185, 'Clockwork Orange, A (1971)',                 'Crime|Drama|Sci-Fi|Thriller',            4.06),
(188, 'Full Metal Jacket (1987)',                   'Action|Drama|War',                       4.00),
(194, 'Terminator, The (1984)',                     'Action|Sci-Fi|Thriller',                 4.11),
(195, 'Terminal, The (2004)',                       'Comedy|Drama|Romance',                   3.50),
(197, 'Graduate, The (1967)',                       'Drama|Romance',                          3.87),
(198, 'Nikita (La Femme Nikita) (1990)',            'Action|Thriller',                        3.91),
(199, 'Foul Play (1978)',                           'Comedy|Thriller',                        3.14),
(200, 'Shiloh (1997)',                              'Children''s|Drama',                      3.10)
ON CONFLICT (id) DO UPDATE
    SET title = EXCLUDED.title,
        genres = EXCLUDED.genres,
        avg_rating = EXCLUDED.avg_rating;
